### ISSUE TITLE
Model hash needs to be included among the metadata

### ISSUE THREAD

**Issue by nicknack23** [cocktailpeanut/breadboard#12]
Identifying the model used to generate the image is arguably just as important as knowing the prompt and seed. Currently though breadboard only displays the model name, which is frequently not even included in the metadata (at least my default setup of automatic1111 does not include model name). But model hash is almost always present in the metadata, so breadboard should display it and also allow search and navigation by hash.

If you need to save space in breadboard's metadata display I think it would be OK to combine model name and hash on the same line, like this:

model_name:	HassanBlend1.4 (4cf12f5d)

**Comment by Grokstreet** [comment]
It would be useful to include the hypernetwork + strength as well

**Comment by cocktailpeanut** [comment]
The `model_hash` attribute was added for a major new version just released today: https://www.reddit.com/r/StableDiffusion/comments/10a3ryo/releasing_breadboard_020_codename_filterverse_a/

Try it out and let me know if it solves your problem. And if it doesn't, feel free to reopen the issue. For now closing. Thanks!

p.s.

@Grokstreet hypernetwork information doesn't seem to be included in any of the metadata. do you have an image that includes this metadata info? If you do, feel free to open a new issue with a zipped image (must be zipped because otherwise the metadata will be stripped)
