### ISSUE TITLE
wasted time when adding many folders to the sources

### ISSUE THREAD

**Issue by redyandsalted** [cocktailpeanut/breadboard#13]
Because I have used many different UIs and have my files scattered in many folders, the process of syncing breadboard took a very long time. This is because every time I added a folder, breadboard would resync with every folder it had listed, even if I had only added one small folder.
My proposed solutions:
1) only sync the new folder, instead of all folders
2) don't sync automatically, make the user click a sync button after adding all of their folders

I prefer 2 because it would allow users to add them all, and then minimise the program when they start the sync.

**Comment by cocktailpeanut** [comment]
Good point, will think about this for the next release.

Also if anyone else stumbles upon this issue and have ideas, please feel free to share.

**Comment by Nixonpolska** [comment]
Yeah. I agree with this idea. It would have been much faster that way.

**Comment by cocktailpeanut** [comment]
This was fixed with today's new release: https://www.reddit.com/r/StableDiffusion/comments/10a3ryo/releasing_breadboard_020_codename_filterverse_a/

Here's how the new sync works:

1. When you add a folder, it displays a "synchronize" button but does NOT automatically sync, so you can add multiple folders and later synchronize them altogether on your own terms
2. When you DO synchronize, it does NOT re-index everything else, it only adds the new folders and synchronizes them only, making everything much more efficient.
3. When you remove a folder, it synchronizes silently WITHOUT re-indexing. It just works
4. Each folder now has its own "re-index" button, meaning if something goes wrong with one folder, you don't have to re-index the whole thing, but just that folder.

Closing for now, feel free to comment to let me know if it solved your problem, and if it didn't, feel free to reopen. Thanks!

**Comment by redyandsalted** [comment]
awesome update, thanks!
