### ISSUE TITLE
When I delete file from the widows explorer folder it never get updated

### ISSUE THREAD

**Issue by Maxlo24** [cocktailpeanut/breadboard#2]
This will be a very interesting tool ! 

After testing it there is some fiew things that would be interesting to add:

- Really update with what is actualy inside the folders (even if I remove the folder and add it agin in the parameters it's not getting updated with the removed files).
- Having shortcut to be able to switch from one image to the next as well as deleting them (using the arrows or custom shortcuts). 
- Being abble to quickly copy the prompt, seed, negatives etc (maybe a button).
- When I add a folder that contains a lot of other folder it would be nice if all the folder get read.

The research bar is very nice and useful ! thanks for developing this tool.
Good luck !

**Comment by cocktailpeanut** [comment]
This should be fixed with the release 0.1.0 today.

More on the release here: https://www.reddit.com/r/StableDiffusion/comments/102ca1u/breadboard_a_stablediffusion_browser_version_010/


> Really update with what is actualy inside the folders (even if I remove the folder and add it agin in the parameters it's not getting updated with the removed files).

When you delete a file, you can run "re-index" to reindex the db freshly https://breadboard.me/docs/#/?id=re-indexing-folders

> Having shortcut to be able to switch from one image to the next as well as deleting them (using the arrows or custom shortcuts).

This was added in version 0.1.0. Now you can use arrow keys to move around, and ctrl-click to multi select. and press "del" key to delete items.

> Being abble to quickly copy the prompt, seed, negatives etc (maybe a button).

This was also added, now when you hover over metadata attributes, they will each display a "copy" button

> When I add a folder that contains a lot of other folder it would be nice if all the folder get read.

This was added too, "recursive folder add" => just add one folder and all its child folders are added automatically.

To learn more, check out the release notes: https://github.com/cocktailpeanut/breadboard/releases/tag/0.1.0

If this resolved your issue, please let me know and close it!
