### ISSUE TITLE
Does not handle files with special characters - ex: apostrophe

### ISSUE THREAD

**Issue by joetech** [cocktailpeanut/breadboard#42]
This seems to fail to load any image with an apostrophe in it.

![image](https://user-images.githubusercontent.com/1650878/215351674-501cf90c-ab0f-4ddc-81aa-bee90c187acc.png)

**Comment by cocktailpeanut** [comment]
@joetech are you using the latest release? https://github.com/cocktailpeanut/breadboard/releases/tag/0.2.1

If you are, and still experiencing the problem, could you post an image sample I can try (with metadata in tact)? That would help me debug.

**Comment by joetech** [comment]
When it runs, I see that is is and I just installed today.
`UP TO DATE 0.2.1 0.2.1`

Here's the prompt.  Of course, the image and text file names both have the `’` in them, BUT... the more I look, the more it seems  it's caching things and if I delete a file manually, (or rename it), Breadboard still tries to load it, but it's not found, of course.  I re-indexed and closed and opened Breadboard, but had no luck.
```professional model headshot of a man with a 5 o’clock shadow
Negative prompt: (bad_prompt:0.8)
Steps: 20, Sampler: Euler a, CFG scale: 7, Seed: 3011333145, Size: 512x512, Model hash: db4e1c64ca, Model: realisticVisionV11_v11
```

It's worth noting that the problem was likely a grid image with `{` or `%` or ??? in it because I used the following Jinja2 wildcard prompt to generate these.
```{% for beard in wildcard("__jumbo/people/beards__") %}
        {% prompt %}professional model headshot of a man with a {{ beard }}{% endprompt %}
    {% endfor %}
```
Once I deleted the broken image references in the gallery view in Breadboard, it was fine, but it feels like re-indexing is not removing files that were renamed/deleted outside of Breadboard.

Now if I could just figure out how to get the prompt labels to show back up like I saw in the v0.1.0 video.  I may look into submitting PRs if I see something I think I can fix/improve.

**Comment by cocktailpeanut** [comment]
@joetech Hi I'm kind of confused about the situation after reading this comment, are you saying it is still caused by the apostrophe in the filename, or are you saying you now think it's caused by your jinja template in the prompt?

Also, how does this template thing work for prompts? You enter it into Auto1111 and it automatically parses the template? I am sure it's not part of the core auto1111 prompt syntax, so guessing you're using some plugin? Would appreciate if you can share what exactly is happening here, would love to learn more so I can replicate.

p.s.

When breadboard reindexes, it literally deletes the entire DB and starts completely from scratch. Here's what happens when you reindex:

1. Delete the entire files DB https://github.com/cocktailpeanut/breadmachine/blob/main/views/settings.ejs#L232
2. Get the list of all CURRENTLY existing files under the folders you've connected https://github.com/cocktailpeanut/breadmachine/blob/main/ipc.js#L84-L88
3. Crawl through the list and index

So it is impossible for breadboard to cache anything. The "cache" is the DB, and as demonstrated above, the whole re-indexing starts from deleting the DB altogether.

**Comment by joetech** [comment]
Yeah.  I believe the prompt code for the [Jinja2 Templates](https://github.com/adieyal/sd-dynamic-prompts/blob/eb35768b8c858e4ddce509ae46834502cf1dd616/jinja2.md) prompt ends up in the file name of the grid image SD creates, which is part of the [Stable Diffusion Dynamic Prompts extension](https://github.com/adieyal/sd-dynamic-prompts).

This is what the one I just generated looks like:
![image](https://user-images.githubusercontent.com/1650878/215612356-c602a2f8-e653-4960-a08a-5db2398badfa.png)

In any case, it's not happening, now, so maybe it was a fluke.  I'm closing this.  Sorry for the noise.
