### ISSUE TITLE
Does not support long file names in Windows

### ISSUE THREAD

**Issue by jnojack** [cocktailpeanut/breadboard#5]
Windows 11. 

Problem: the metadata for the image is displayed, but the image does not. It displays the missing image icon instead.

I determined that the files that are affected all have extremely long file names as created by the UI I use. They are like this:

\Users\jilln\Desktop\stable-diffusion-webui\outputs\txt2img-images\00466-2685178687-{highly detailed)+++, (hyper realistic)+++, full length photograph of angry forty year old stheno having curly shoulder length h.png

I alter to something shorter, like this:

\Users\jilln\Desktop\stable-diffusion-webui\outputs\txt2img-images\00466-2685178687-{highly detailed)+++, (hyper realistic)+++, angry stheno.png

and the missing image fills in on a refresh.

Thanks for your fab program! Nice work for a weekend coding project :-)

**Comment by cocktailpeanut** [comment]
Thanks for reporting @jnojack. I looked into this and turns out it's not because of the long file name, but because of the `+` sign. There's a URL encoding issue.

I've just fixed this in dev, and the fix will be included in the next release, will update this issue when it does. soon.

**Comment by jnojack** [comment]
And this is why are a dev and I am just a greatful user. Many thanks.

**Comment by cocktailpeanut** [comment]
@jnojack This should be fixed with the version 0.1.0 release today. Check out the announcement here: https://www.reddit.com/r/StableDiffusion/comments/102ca1u/breadboard_a_stablediffusion_browser_version_010/

And the full release note here: https://github.com/cocktailpeanut/breadboard/releases/tag/0.1.0

Please let me know if this was fixed and feel free to close the issue

**Comment by cocktailpeanut** [comment]
Closing now, please reopen if this was not fixed on your end.
